on: pull_request
name: Translations Workflow
jobs:
  formatCode:
    name: Translate Strings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: translate strings
        uses: ./.github/actions/action-gtranslate
        with:
          translationKey: 'AIzaSyDBzuLnStbM-GJv7ILmACyS_8l3kzz2ez4'
          outputLanguages: 'es,fr,zh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
