on: pull_request
name: Translations Workflow
jobs:
  formatCode:
    name: Translate Strings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.LEIAPIX_ADMINS_SSH_PRIVATE_KEY }}
      - name: translate strings
        uses: ./
        with:
          translationKey: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          outputLanguages: 'es,fr,zh'
          resDirectories: 'test_app/app/src/main/res/'